### ISSUE TITLE
你这是做的aimp歌词下载插件？

### ISSUE THREAD

**Issue by ashi876** [Satroki/AimpLyrics#1]
神人啊，干嘛不做完呢？大家需要你

**Comment by Satroki** [comment]
@ashi876 只写了本地歌词，懒了，坑了😐

**Comment by AlfredXiangWu** [comment]
@Satroki 懒死你，赶紧填坑2333

**Comment by ashi876** [comment]
能做个本地能读标签的也行啊。项目进行到哪步了？能编个能用的么。我觉得有个能读内嵌的浮动式滚动歌词插件就很棒了。

**Comment by ashi876** [comment]
thanks.我已经开始学习编程了。正好学习学习大大的源代码
