### ISSUE TITLE
简单实用，蛮好的

### ISSUE THREAD

**Issue by ashi876** [Satroki/AimpLyrics#2]
我就喜欢这种风格的。如果能读内嵌歌词就完美了

请问大大还会有后续么？

**Comment by Satroki** [comment]
@ashi876 读内嵌歌词我写了呢，读不出来？

**Comment by ashi876** [comment]
读不出来。用的4.5beta也许bug多。.明天我下个正式版试试

**Comment by ashi876** [comment]
@Satroki 早上回滚到正式版。内嵌歌词正常了，干净的介面用的很爽，最讨厌一堆没用功能占地方的东东

在beta版一下一堆报错，这个aimpBeta本身一堆错，根本就是个alpha版。就别管它了，再次感谢
